# Generated by Django 3.1.7 on 2021-08-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=15)),
                ('l_name', models.CharField(max_length=15)),
                ('personal_id', models.BigIntegerField()),
                ('mobile_num', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('subscription', models.CharField(choices=[('200', '200 Mbps'), ('500', '500 Mbps'), ('1000', '1Gbps')], default='200', max_length=4)),
                ('charge_from', models.DateField(auto_now_add=True)),
                ('program_cost', models.IntegerField()),
            ],
        ),
    ]
