# Generated by Django 3.1.7 on 2021-08-20 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.CharField(choices=[('200', '200 Mbps'), ('500', '500 Mbps'), ('1000', '1Gbps')], default='200', max_length=4)),
                ('charge_from', models.DateField(auto_now_add=True)),
                ('program_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=15)),
                ('l_name', models.CharField(max_length=15)),
                ('personal_id', models.BigIntegerField(default=100000000, unique=True)),
                ('mobile_num', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('related_program', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='net_comm_web.program')),
            ],
        ),
    ]
