# Generated by Django 3.1.7 on 2021-08-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_comm_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='personal_id',
            field=models.BigIntegerField(default=100000000),
        ),
    ]
