# Generated by Django 3.1.7 on 2021-08-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_comm_web', '0002_customer_personal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='personal_id',
            field=models.BigIntegerField(default=100000000, unique=True),
        ),
    ]
