# Generated by Django 3.1.7 on 2021-08-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_comm_web', '0004_auto_20210825_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='f_name',
            field=models.CharField(max_length=15),
        ),
    ]
